name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    if: github.run_id != 1
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/cicd-dotnet.yml@1.0.1
    with:
      enableSonarQube: true
      dotnet-logging: ${{ inputs.dotnet-logging }}
      dotnet-version: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      solution: ./Logging.XUnit.sln
    secrets: inherit
